### ISSUE TITLE
Adding a comment failing

### ISSUE THREAD

**Issue by kzzztkt** [Rim0Rad/FeatherQuest#101]
# adding a comment fails 

### Repro steps

1. Open app 
2. Go to sightings 
3. Click a bird
4. Go to add a comment
5. Receive error *'There was an error posting your comment. Please try again later'*

### acceptance criteria:
User should be able to add a comment

![IMG_0107](https://github.com/Rim0Rad/FeatherQuest/assets/90208920/91f90ce0-f123-41a8-9ebb-1320c911b524)

**Comment by wallace-y** [comment]
@kzzztkt Unable to recreate the issue on Android currently. If you are able to double check after your next pull that this is still an issue and I will investigate further

**Comment by wallace-y** [comment]
Can't recreate on Iphone as well

**Comment by kzzztkt** [comment]
Fixed
