### ISSUE TITLE
Opening the Sighting.jsx page on main branch results in an error

### ISSUE THREAD

**Issue by wallace-y** [Rim0Rad/FeatherQuest#24]
Testing on Andorid with Expo Go on phone

Steps to recreate
- Run npx expo start on main branch
- Click the 'post sighting" button

![image](https://github.com/Rim0Rad/FeatherQuest/assets/111649895/bf56cae6-3425-4617-bc8c-f3a788cda03f)

- results in an error "cannot read property of common_name of undefined

![Screenshot_20230615-075821_Expo Go](https://github.com/Rim0Rad/FeatherQuest/assets/111649895/092eac6e-b5a4-4a63-af74-c2f8a2d9dca8)

**Comment by wallace-y** [comment]
@SimonForshaw tagging for reference but we can go through as a team and work out who can pick up

**Comment by SimonForshaw** [comment]
Rimas is working on the post sighting button. I think Sighting.jsx may have been linked there in error as you need to navigate to it through SightingList.jsx to have the information passed through the pages. if that makes sense

**Comment by wallace-y** [comment]
Resolved
