### ISSUE TITLE
Some of the sightings on the maps are located in other countries ( which is not a huge issues) but one of them is in the north sea.

### ISSUE THREAD

**Issue by SimonForshaw** [Rim0Rad/FeatherQuest#57]
![Screenshot 2023-06-18 214837](https://github.com/Rim0Rad/FeatherQuest/assets/97294546/cd944717-dfe4-48f7-9b44-4f749874332c)
![Screenshot 2023-06-18 214857](https://github.com/Rim0Rad/FeatherQuest/assets/97294546/06c37878-540e-4fc0-9c98-222165541aec)
![Screenshot 2023-06-18 214909](https://github.com/Rim0Rad/FeatherQuest/assets/97294546/fdc5acad-0d06-495b-a5d6-60cad1ad6012)

**Comment by wallace-y** [comment]
Manual exercise in the DB but the coordinates should all now be within the UK
